#!/bin/bash
#SBATCH --job-name=stepEcHd1
#SBATCH --account=pet-gspt-2019
#SBATCH --partition=nodes
#SBATCH --time=02:00:00
#SBATCH --ntasks=8
#SBATCH --cpus-per-task=16
#SBATCH --mem-per-cpu=500mb
ulimit -s unlimited
export OMP_NUM_THREADS=$SLURM_CPUS_PER_TASK
echo "Running GS2 code with ${SLURM_NTASKS} tasks and ${SLURM_CPUS_PER_TASK} cpus per task."
mpiexec -n ${SLURM_NTASKS} /users/mly509/gs2/bin/gs2 input.in>&out.txt
