#!/bin/bash 

#SBATCH --job-name=linear
#SBATCH --account=PHYS-GSPT-2019
#SBATCH --time=02:00:00
#SBATCH --ntasks=6
#SBATCH --cpus-per-task=1
#SBATCH --partition=nodes 
#SBATCH --mem-per-cpu=5GB
ulimit -s unlimited
export OMP_NUM_THREADS=1
mpirun -n $SLURM_NTASKS  /users/mly509/gs2/bin/gs2 gxLinCbc2.in >& out.txt
